version: '3'

services:
  fpm:
    image: 'akeneo/fpm:php-7.3'
    environment:
      COMPOSER_HOME: '/home/docker/.composer'
      PHP_IDE_CONFIG: 'serverName=pim-ce-cli'
      PHP_XDEBUG_ENABLED: 1
      PHP_XDEBUG_IDE_KEY: 'PHPSTORM'
      PHP_XDEBUG_REMOTE_HOST: '10.254.254.254'
    user: docker
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - 'symfony'

  httpd:
    image: 'httpd:2.4'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP}:80'
    volumes:
      - './:/app:ro'
      - './docker/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/app.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'symfony'

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - 'symfony'
    ports:
      - '${MYSQL_PORT}:3306'

  node:
    image: 'node:10-slim'
    user: 'node'
    volumes:
      - './:/app'
    working_dir: '/app'
    networks:
      - 'symfony'

networks:
  symfony: